services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    ports:
      - "3001:3001"
    volumes:
      - /cosmos-storage/uptime-kuma:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "extra/healthcheck"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 180s
